apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: spark
spec:
  hard:
    requests.cpu: "1"      
    requests.memory: "1Gi" 
    limits.cpu: "10"         
    limits.memory: "10Gi"  
