apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod
  namespace: high-priority-namespace
spec:
  containers:
    - name: high-priority-container
      image: busybox
      resources:
        requests:
          memory: "2000Mi"
          cpu: "1"
        limits:
          memory: "2000Mi"
          cpu: "1"
      command: ["sh", "-c", "sleep 3600"]
  priorityClassName: high-priority
