apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-1
  namespace: low-priority-namespace
spec:
  containers:
  - name: low-priority-container-1
    image: busybox
    resources:
      requests:
        memory: "2000Mi"
        cpu: "500m"
      limits:
        memory: "2000Mi"
        cpu: "500m"
    command: ["sh", "-c", "sleep 3600"]
  priorityClassName: low-priority
---
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-2
  namespace: low-priority-namespace
spec:
  containers:
  - name: low-priority-container-2
    image: busybox
    resources:
      requests:
        memory: "2000Mi"
        cpu: "500m"
      limits:
        memory: "2000Mi"
        cpu: "500m"
    command: ["sh", "-c", "sleep 3600"]
  priorityClassName: low-priority
