apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: aws-s3
  namespace: spark
spec:
  type: Python
  mode: cluster
  image: spark-aws-image
  mainApplicationFile: local:///opt/spark/source/code.py
  sparkVersion: 3.5.2
  restartPolicy:
    type: OnFailure
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark
    annotations:
      yunikorn.apache.org/queue: root.spark.child1
      yunikorn.apache.org/schedulingPolicyParameters: "placeholderTimeoutInSeconds=300 gangSchedulingStyle=Hard"
      yunikorn.apache.org/task-group-name: "spark-driver"
      yunikorn.apache.org/task-groups: |-
        [{
            "name": "spark-driver",
            "minMember": 1,
            "minResource": {
              "cpu": "1",
              "memory": "1Gi"
            },
            "nodeSelector": {},
            "tolerations": [],
            "affinity": {},
            "topologySpreadConstraints": []
         },
         {
            "name": "spark-executor",
            "minMember": 1,
            "minResource": {
              "cpu": "1",
              "memory": "1Gi"
            }
         }]
    labels:
      version: 3.5.2
    envVars:
      AWS_ACCESS: "your key"
      AWS_SECRET: "your key"
  executor:
    cores: 1
    memory: 512m
    instances: 1
    annotations:
      yunikorn.apache.org/task-group-name: "spark-executor"
    envVars:
      AWS_ACCESS: "your key"
      AWS_SECRET: "your key"
